### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by tomassasovsky** [hwtnb/SylphyHornPlusWin11#2]
I'm getting this error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName)
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal21313.<GetDesktops>d__3.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SylphyHorn.Services.SettingsService.ResizeList()
   at SylphyHorn.Services.HookService.Suspend()
   at SylphyHorn.ApplicationPreparation.<CreateTaskTrayIcon>g__ShowSettings|15_0()
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SylphyHorn
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/SylphyHorn.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
MetroTrilithon
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/MetroTrilithon.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.ApplicationInsights
    Assembly Version: 2.19.0.227
    Win32 Version: 2.19.0.00227
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/Microsoft.ApplicationInsights.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
StatefulModel
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/StatefulModel.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MetroRadiance
    Assembly Version: 2.4.1.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/MetroRadiance.DLL
----------------------------------------
MetroTrilithon.Desktop
    Assembly Version: 0.3.1.0
    Win32 Version: 0.3.1.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/MetroTrilithon.Desktop.DLL
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
Livet.Mvvm
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/Livet.Mvvm.DLL
----------------------------------------
SylphyHorn.Core
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/SylphyHorn.Core.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
VirtualDesktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/VirtualDesktop.DLL
----------------------------------------
GregsStack.InputSimulatorStandard
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/GregsStack.InputSimulatorStandard.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MetroRadiance.Core
    Assembly Version: 2.4.1.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/MetroRadiance.Core.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Open.WinKeyboardHook
    Assembly Version: 1.0.14.0
    Win32 Version: 1.0.14.0
    CodeBase: file:///C:/Users/Tomas/OneDrive/Documents/SylphyHorn/lib/Open.WinKeyboardHook.DLL
----------------------------------------
VirtualDesktop.22000.generated
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Tomas/AppData/Local/grabacr.net/VirtualDesktop/assemblies/VirtualDesktop.22000.generated.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by hwtnb** [comment]
@tomassasovsky Thank you for your report.

I need more information to solve this issue clearly.

* Windows version and build number
* Whether you used other SylphyHorns (the original or forks) or not
* How frequently the bug appears, the circumstances that seem to trigger it, etc.

I have released [beta.4](https://github.com/hwtnb/SylphyHornPlusWin11/releases/tag/v4.0.0-beta.4). it includes some bugfixes and improvements.

Note: Update from the original or other forks
Please delete cache data (VirtualDesktop.*****.generated.dll) at %UserProfile%\AppData\Local\grabacr.net\SylphyHorn\assemblies before SylphyHornPlus starts.

**Comment by jritmeijer-muhimbi** [comment]
I had the same error (beta 4) when opening the settings screen. 

Then I removed all folders from %UserProfile%\AppData\Local\grabacr.net\

It no longer crashes when opening the Settings screen. 

Unfortunately, the most important functionality for me (move the current window to another desktop) doesn't work.

I am on Windows 11 Build 22000.469

**Comment by hwtnb** [comment]
@jritmeijer-muhimbi Its functionality works on my devices (build 22000.438, 22538.1010 and 22543.1000).

Please let me know the following:
* [App log] message on the Settings window if errors occur.
* Key bindings that you assigned.

Note:
* Shortcuts functionality is disabled when the Settings window is open. (I plan to change this specification)
* You have to run SylphyHornPlus as an administrator to move an active window with administrator privileges.

**Comment by ariccb** [comment]
I am having the same issue, and I've tried removing that file in the assemblies folder you mention in the release notes. I have tried removing all files from all other versions (I previously tried the original SylphHorn project, but it didn't work on Win11. This is for my work computer. My home computer is Win11 and this fork works for me. Not sure why i'm getting an exception on this computer.

**Comment by jritmeijer-muhimbi** [comment]
>>Shortcuts functionality is disabled when the Settings window is open. (I plan to change this specification)

That explains. I was testing with the Settings window open. Once I close it it works fine. Ui of the SylphyhornEx I used previously is better though, but for now I am just happy I got something that works.

**Comment by bobsage123** [comment]
> I had the same error (beta 4) when opening the settings screen.
> 
> Then I removed all folders from %UserProfile%\AppData\Local\grabacr.net\
> 
> It no longer crashes when opening the Settings screen.
> 
> Unfortunately, the most important functionality for me (move the current window to another desktop) doesn't work.
> 
> I am on Windows 11 Build 22000.469

I have the opposite issue as you. I get the above .NET error when going to settings. But the "switch window to other desktop" shortcut works fine. I've tried clearing out that appdata folder.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SylphyHorn.Serialization.SerializationExtensions.GetOrDefault(WallpaperPathProperty path)
   at SylphyHorn.UI.Bindings.WallpaperViewModel..ctor(VirtualDesktop desktop, WallpaperPathProperty path, WallpaperPositionsProperty position)
   at SylphyHorn.UI.Bindings.VirtualDesktopViewModel..ctor(Int32 index, VirtualDesktop desktop)
   at SylphyHorn.UI.Bindings.VirtualDesktopViewModel.<>c.<CreateAll>b__37_0(VirtualDesktop d, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SylphyHorn.UI.Bindings.SettingsWindowViewModel..ctor(HookService hookService)
   at SylphyHorn.ApplicationPreparation.ShowSettings()
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SylphyHorn
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/SylphyHorn.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
MetroTrilithon
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/MetroTrilithon.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.ApplicationInsights
    Assembly Version: 2.20.0.103
    Win32 Version: 2.20.0.00103
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Microsoft.ApplicationInsights.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
StatefulModel
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/StatefulModel.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MetroRadiance
    Assembly Version: 2.4.1.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/MetroRadiance.DLL
----------------------------------------
MetroTrilithon.Desktop
    Assembly Version: 0.3.1.0
    Win32 Version: 0.3.1.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/MetroTrilithon.Desktop.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
Livet.Mvvm
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.Mvvm.DLL
----------------------------------------
SylphyHorn.Core
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/SylphyHorn.Core.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
VirtualDesktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/VirtualDesktop.DLL
----------------------------------------
GregsStack.InputSimulatorStandard
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/GregsStack.InputSimulatorStandard.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MetroRadiance.Core
    Assembly Version: 2.4.1.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/MetroRadiance.Core.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Open.WinKeyboardHook
    Assembly Version: 1.0.14.0
    Win32 Version: 1.0.14.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Open.WinKeyboardHook.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
VirtualDesktop.22000.generated
    Assembly Version: 1.0.0.21359
    Win32 Version: 1.0.0.21359
    CodeBase: file:///C:/Users/owner/AppData/Local/grabacr.net/SylphyHorn/assemblies/VirtualDesktop.22000.generated.dll
----------------------------------------
MetroRadiance.Chrome
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/MetroRadiance.Chrome.DLL
----------------------------------------
Microsoft.Xaml.Behaviors
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.39.4716
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Microsoft.Xaml.Behaviors.DLL
----------------------------------------
Livet.Behaviors
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.Behaviors.DLL
----------------------------------------
Livet.Core
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.Core.DLL
----------------------------------------
Livet.Messaging
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.Messaging.DLL
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
Livet.EventListeners
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.EventListeners.DLL
----------------------------------------
Livet.Collections
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2
    CodeBase: file:///C:/Users/owner/Desktop/SylphyHornPlus-Ver4.0.0-beta.5/SylphyHorn/lib/Livet.Collections.DLL
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by ertyz** [comment]
First run, administrator's rights, all caches purged.
I can see icon in taskbar, but when I try open settings same issue log with @bobsage123 happen
Windows 11 21H2 x64
beta v5

**Comment by rikrdo89** [comment]
I have same issue as @bobsage123 and @ertyz  in win 11 21H2 x64 and V4beta9. 
I opened a new issue (https://github.com/hwtnb/SylphyHornPlusWin11/issues/23) but it may be a duplicate from this threat.

**Comment by pritam4249** [comment]
Any update in this? I also have the same issue.
