### ISSUE TITLE
can't open settings GUI in v4.beta9

### ISSUE THREAD

**Issue by rikrdo89** [hwtnb/SylphyHornPlusWin11#23]
On windows 11, program works ok, I am able to move active windows to virtual desktops, but whenever I want to open the settings GUI from the tray, I get an "unhandled exception error". See screenshots:

![image](https://user-images.githubusercontent.com/24930604/209866124-b965509c-2b8e-4b5c-886e-f2fbd0298c8f.png)

![image](https://user-images.githubusercontent.com/24930604/209866108-ac3ef1e2-a497-422e-941e-eb4041269657.png)

**Comment by rikrdo89** [comment]
See error log below:

************** Exception Text **************
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Markup.StaticExtension' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'SylphyHorn.Services.WallpaperService' threw an exception. ---> System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {7693E886-51C9-4070-8419-9F70738EC8FA} from the IClassFactory failed due to the following error: 8000ffff Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SylphyHorn.Services.ClsidImageFormatSupportDetector.GetValue()
   at SylphyHorn.Services.ImageFormatSupportDetector.get_IsSupported()
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at SylphyHorn.Services.WallpaperService.CreateSupportFormatText()
   at SylphyHorn.Services.WallpaperService..cctor()
   --- End of inner exception stack trace ---
   at SylphyHorn.Services.WallpaperService.get_SupportedFileTypes()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SylphyHorn.ApplicationPreparation.ShowSettings()
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by john-brice** [comment]
Same on Windows 10 22H2 19045.3693 with v4.beta12

**Comment by pritam4249** [comment]
any update in this? I also got the same issue
